version: '3.8'

services:
  panfm:
    build: .
    container_name: panfm
    ports:
      - "3000:3000"
    volumes:
      # Persist data files (create these as files first, not directories)
      # Run setup.sh or touch these files before starting: settings.json devices.json encryption.key auth.json
      - ./settings.json:/app/settings.json
      - ./devices.json:/app/devices.json
      - ./encryption.key:/app/encryption.key
      - ./auth.json:/app/auth.json
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    restart: unless-stopped
    # Override CMD for development with auto-reload
    command: python app.py
